{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/1016","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/1016/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/1016/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/1016/events","html_url":"https://github.com/elastic/elasticsearch/issues/1016","id":1036160,"node_id":"MDU6SXNzdWUxMDM2MTYw","number":1016,"title":"Merging complex objects / types (geo, objects) can cause failure to lookup field names (without type prefix)","user":{"login":"tozz","id":705677,"node_id":"MDQ6VXNlcjcwNTY3Nw==","avatar_url":"https://avatars0.githubusercontent.com/u/705677?v=4","gravatar_id":"","url":"https://api.github.com/users/tozz","html_url":"https://github.com/tozz","followers_url":"https://api.github.com/users/tozz/followers","following_url":"https://api.github.com/users/tozz/following{/other_user}","gists_url":"https://api.github.com/users/tozz/gists{/gist_id}","starred_url":"https://api.github.com/users/tozz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tozz/subscriptions","organizations_url":"https://api.github.com/users/tozz/orgs","repos_url":"https://api.github.com/users/tozz/repos","events_url":"https://api.github.com/users/tozz/events{/privacy}","received_events_url":"https://api.github.com/users/tozz/received_events","type":"User","site_admin":false},"labels":[{"id":23173,"node_id":"MDU6TGFiZWwyMzE3Mw==","url":"https://api.github.com/repos/elastic/elasticsearch/labels/%3Ebug","name":">bug","color":"b60205","default":false,"description":null},{"id":109790,"node_id":"MDU6TGFiZWwxMDk3OTA=","url":"https://api.github.com/repos/elastic/elasticsearch/labels/v0.16.3","name":"v0.16.3","color":"DDDDDD","default":false,"description":null},{"id":97023,"node_id":"MDU6TGFiZWw5NzAyMw==","url":"https://api.github.com/repos/elastic/elasticsearch/labels/v0.17.0","name":"v0.17.0","color":"DDDDDD","default":false,"description":null}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2011-06-10T12:01:49Z","updated_at":"2011-06-10T17:01:14Z","closed_at":"2011-06-10T17:01:14Z","author_association":"NONE","active_lock_reason":null,"body":"When specifying a geo_point type in 16.2 geo_distance facet fails. Example works in 16.1 and 16.0\nError: FacetPhaseExecutionException[Facet [geotest]: No mapping found for field [locations]]\n\nCurl recreation at https://gist.github.com/2ba2e3d0d50a5e4c777c\nThe empty document does throw an error but the bug is reproducible even with a non-empty document.\n","closed_by":{"login":"kimchy","id":41300,"node_id":"MDQ6VXNlcjQxMzAw","avatar_url":"https://avatars1.githubusercontent.com/u/41300?v=4","gravatar_id":"","url":"https://api.github.com/users/kimchy","html_url":"https://github.com/kimchy","followers_url":"https://api.github.com/users/kimchy/followers","following_url":"https://api.github.com/users/kimchy/following{/other_user}","gists_url":"https://api.github.com/users/kimchy/gists{/gist_id}","starred_url":"https://api.github.com/users/kimchy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kimchy/subscriptions","organizations_url":"https://api.github.com/users/kimchy/orgs","repos_url":"https://api.github.com/users/kimchy/repos","events_url":"https://api.github.com/users/kimchy/events{/privacy}","received_events_url":"https://api.github.com/users/kimchy/received_events","type":"User","site_admin":false},"performed_via_github_app":null}