{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/12009","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/12009/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/12009/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/12009/events","html_url":"https://github.com/elastic/elasticsearch/issues/12009","id":92796599,"node_id":"MDU6SXNzdWU5Mjc5NjU5OQ==","number":12009,"title":"ES Memory Breaker","user":{"login":"shaman478","id":9427526,"node_id":"MDQ6VXNlcjk0Mjc1MjY=","avatar_url":"https://avatars3.githubusercontent.com/u/9427526?v=4","gravatar_id":"","url":"https://api.github.com/users/shaman478","html_url":"https://github.com/shaman478","followers_url":"https://api.github.com/users/shaman478/followers","following_url":"https://api.github.com/users/shaman478/following{/other_user}","gists_url":"https://api.github.com/users/shaman478/gists{/gist_id}","starred_url":"https://api.github.com/users/shaman478/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/shaman478/subscriptions","organizations_url":"https://api.github.com/users/shaman478/orgs","repos_url":"https://api.github.com/users/shaman478/repos","events_url":"https://api.github.com/users/shaman478/events{/privacy}","received_events_url":"https://api.github.com/users/shaman478/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2015-07-03T05:36:13Z","updated_at":"2015-07-03T05:52:21Z","closed_at":"2015-07-03T05:52:20Z","author_association":"NONE","active_lock_reason":null,"body":"Hello all,\n\nWe are running Graylog server v1.01 and Graylog-web-interface v1.01on ES v1.4.4 on SLES 11 SP3 platform, today we logon graylog-web-interface and found HTTP 400 error, \n\nthe ES logs as below:\n\n[2015-07-03 10:03:03,415][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646251060 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:03,443][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646253680 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:03,449][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646252426 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:03,455][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646251888 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:03,785][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 651460534 [621.2mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:05,902][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 649663091 [619.5mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:06,489][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646252146 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n[2015-07-03 10:03:06,533][WARN ][indices.breaker          ] [FIT CN ES Node] [FIELDDATA] New used memory 646251688 [616.3mb] from field [timestamp] would be larger than configured breaker: 633785548 [604.4mb], breaking\n\nwe think that's the ES memory breaker setting as below link described:\nhttps://www.elastic.co/guide/en/elasticsearch/reference/1.4/index-modules-fielddata.html\n\nwe have some questions:\n1. which parameters should be responsible for our ES error,\n   i mean which parameter we should be change and change to which value? \n2. as ES documents mentioned, all parameter already have default value so why we still have encountered this error ? \n\nThanks for your great support.\n","closed_by":{"login":"dadoonet","id":274222,"node_id":"MDQ6VXNlcjI3NDIyMg==","avatar_url":"https://avatars3.githubusercontent.com/u/274222?v=4","gravatar_id":"","url":"https://api.github.com/users/dadoonet","html_url":"https://github.com/dadoonet","followers_url":"https://api.github.com/users/dadoonet/followers","following_url":"https://api.github.com/users/dadoonet/following{/other_user}","gists_url":"https://api.github.com/users/dadoonet/gists{/gist_id}","starred_url":"https://api.github.com/users/dadoonet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dadoonet/subscriptions","organizations_url":"https://api.github.com/users/dadoonet/orgs","repos_url":"https://api.github.com/users/dadoonet/repos","events_url":"https://api.github.com/users/dadoonet/events{/privacy}","received_events_url":"https://api.github.com/users/dadoonet/received_events","type":"User","site_admin":false},"performed_via_github_app":null}