[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188917063","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188917063","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188917063,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODkxNzA2Mw==","user":{"login":"eskibars","id":2246002,"node_id":"MDQ6VXNlcjIyNDYwMDI=","avatar_url":"https://avatars0.githubusercontent.com/u/2246002?v=4","gravatar_id":"","url":"https://api.github.com/users/eskibars","html_url":"https://github.com/eskibars","followers_url":"https://api.github.com/users/eskibars/followers","following_url":"https://api.github.com/users/eskibars/following{/other_user}","gists_url":"https://api.github.com/users/eskibars/gists{/gist_id}","starred_url":"https://api.github.com/users/eskibars/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/eskibars/subscriptions","organizations_url":"https://api.github.com/users/eskibars/orgs","repos_url":"https://api.github.com/users/eskibars/repos","events_url":"https://api.github.com/users/eskibars/events{/privacy}","received_events_url":"https://api.github.com/users/eskibars/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T18:19:44Z","updated_at":"2016-02-25T18:19:44Z","author_association":"CONTRIBUTOR","body":"@roytmana you're likely interested in https://github.com/elastic/elasticsearch/issues/12721 .  The transport-wares plugin is aged and we're not seeing a lot of real usage of it out in the community\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188918659","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188918659","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188918659,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODkxODY1OQ==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T18:25:22Z","updated_at":"2016-02-25T18:25:22Z","author_association":"NONE","body":"@eskibars Yeah I seen it and I am not happy it is being discontinued as there are enough people using it. I had to make some changes in the code for it to work with 2.2\n\nI do not think the is related to transport-wares I am pretty sure I will get the same if running standalone ES. I think it is some connectivity issue on my workstation that's causing it and wanted the development team to see the exception because NPE is never a good thing\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188938679","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188938679","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188938679,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODkzODY3OQ==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T19:20:16Z","updated_at":"2016-02-25T19:21:31Z","author_association":"MEMBER","body":"@roytmana Can you provide a minimal reproduction _without_ transport wares? I am not able to reproduce on master nor 2.2 currently (I successfully started an embedded node with TRACE logging turned on and there were not any NPEs in the logs).\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188989994","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188989994","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188989994,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODk4OTk5NA==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T21:08:49Z","updated_at":"2016-02-25T21:08:49Z","author_association":"NONE","body":"@jasontedor it does not need any special reproduction. I just unzipped standard elastic distro and it started it with the same exceptions. I think it is something specific to my workstation when connecting to from localhost to localhost (maybe from ipv6 to ipv4) but in any case elastich should not fail with NPE but handle it better. Attached is log with TRACE level \n\n[elasticsearch.log.txt](https://github.com/elastic/elasticsearch/files/147275/elasticsearch.log.txt)\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188991572","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188991572","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188991572,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODk5MTU3Mg==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T21:14:23Z","updated_at":"2016-02-25T21:14:23Z","author_association":"MEMBER","body":"@roytmana Can you give any more details about your system and config? I'm also running IPv4 and IPv6 and I do not see this issue. While avoiding the NPE is easy here, I want to understand the root cause before addressing.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/188993916","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-188993916","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":188993916,"node_id":"MDEyOklzc3VlQ29tbWVudDE4ODk5MzkxNg==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T21:21:14Z","updated_at":"2016-02-25T21:22:28Z","author_association":"NONE","body":"I wish I could - I am not a networking guru but I think it is the same\nissue I had with some development tool that start jetty on localhost and\nthen tries to connect to it. It fails. I had to force to use my real ipv4\naddress to work. I think it started couple of months ago with one windows\nroutine updates and I think my co-worked is having the same issue with that\ntool after that update. It is only loopback connections that seem to be\nfailing. If you can tell me what to check I will gladly do. I have already\ntried   JDK 7, 8, 32 and 64 bit - no difference I tried to turn ipv6 off\nbut it does not affect loopback it still resolves to ::1 and did not fix\nthe problem ...\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189007551","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189007551","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189007551,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTAwNzU1MQ==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T22:10:28Z","updated_at":"2016-02-25T22:10:28Z","author_association":"NONE","body":"here seems to be similar problem http://superuser.com/questions/962293/cant-connect-to-socket-listening-on-127-0-0-1-but-works-for-localhost-in-wind but no solution\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189030232","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189030232","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189030232,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTAzMDIzMg==","user":{"login":"eskibars","id":2246002,"node_id":"MDQ6VXNlcjIyNDYwMDI=","avatar_url":"https://avatars0.githubusercontent.com/u/2246002?v=4","gravatar_id":"","url":"https://api.github.com/users/eskibars","html_url":"https://github.com/eskibars","followers_url":"https://api.github.com/users/eskibars/followers","following_url":"https://api.github.com/users/eskibars/following{/other_user}","gists_url":"https://api.github.com/users/eskibars/gists{/gist_id}","starred_url":"https://api.github.com/users/eskibars/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/eskibars/subscriptions","organizations_url":"https://api.github.com/users/eskibars/orgs","repos_url":"https://api.github.com/users/eskibars/repos","events_url":"https://api.github.com/users/eskibars/events{/privacy}","received_events_url":"https://api.github.com/users/eskibars/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T23:16:29Z","updated_at":"2016-02-25T23:16:29Z","author_association":"CONTRIBUTOR","body":"@roytmana just FYI, I just tried it on my win10 machine as well (with all the latest MS updates and both ipv6/ipv4) and am not getting this.  Can you give some more detail about your networking setup?\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189036367","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189036367","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189036367,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTAzNjM2Nw==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-25T23:39:26Z","updated_at":"2016-02-25T23:39:26Z","author_association":"NONE","body":"@eskibars it could be the antivirus/local firewall. but I stopped it it did not help. I spent half a couple of months ago trying to figure why service listening on loopback can't be connected to on my workstation (the tool I was using could not be configured on which address to listen and to which to connect) but could not figure it out. Hopefully it is not a widespread issue since your workstation worked fine and my notebook too.\n\nI could send you my ipconfig and anything else you may need but I would prefer to do it privately\nplease let me know what else besides ipconfig /all you would want and where to send it\n\nFor my purposes I just set my node to local mode since it will be a single node embedded deployment and the issue went away of course \n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189146373","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189146373","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189146373,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTE0NjM3Mw==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-26T07:27:24Z","updated_at":"2016-02-26T07:27:24Z","author_association":"MEMBER","body":"I also attempted to reproduce this on a Windows 10 system with the latest updates and it did not reproduce for me. Again, it's really easy to make this NPE go away (without even understanding where it's coming from) but I really want to understand where it's coming from in case it's indicative of a bigger issue and making the NPE go away would just be papering over it.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189295790","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189295790","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189295790,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTI5NTc5MA==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-26T14:12:23Z","updated_at":"2016-02-26T14:12:23Z","author_association":"NONE","body":"Once again let me know what info to collect and where to send it\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189481087","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189481087","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189481087,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTQ4MTA4Nw==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-26T20:58:19Z","updated_at":"2016-02-26T20:59:21Z","author_association":"MEMBER","body":"> Once again let me know what info to collect and where to send it\n\n@roytmana If I made available a custom build of Elasticsearch (or pointed you to a branch that you could build from source (and so see the diffs from v2.2.0)), would you be able to run it and send me the logs? I want to sprinkle additional logging in a couple targeted places to find the source of the channel error that does not have an exception associated with it.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189507322","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189507322","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189507322,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTUwNzMyMg==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-26T22:23:37Z","updated_at":"2016-02-26T22:23:37Z","author_association":"NONE","body":"Yes sure please send me the link to download it\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189680873","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189680873","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189680873,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTY4MDg3Mw==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-27T16:47:06Z","updated_at":"2016-02-27T16:47:06Z","author_association":"MEMBER","body":"> Yes sure please send me the link to download it\n\n@roytmana Thanks. I've created a branch [issue-16810](https://github.com/jasontedor/elasticsearch/tree/issue-16810) in my repository that you can [diff](https://github.com/jasontedor/elasticsearch/commit/d1755be587b6c59d6531cc19d647a6411c1f6ebf) against the [v2.2.0 tag](https://github.com/elastic/elasticsearch/tree/v2.2.0) in the elastic repository. \n\nThe salient changes are some extra logging statements that I hope will give us enough information to track down the root cause of the problem.\n\nI've [uploaded](https://drive.google.com/file/d/0B4tiSXOP8wheN2xVY1g3Slg2a3M/view?usp=sharing) a packaged zip distribution of Elasticsearch from commit [d1755be](https://github.com/jasontedor/elasticsearch/commit/d1755be587b6c59d6531cc19d647a6411c1f6ebf) in that issue-16810 branch. It has the following SHA-256 hash:\n\n```\nd76fe7251b48644fa741b5a3682e0b02b56c539a77fc1fc8984e496d0cb315dc\n```\n\nWhen you start Elasticsearch from the distribution in this zip, it will print a log line that matches\n\n```\n^.*version\\[2.2.1-SNAPSHOT\\], pid\\[[0-9]+\\], build\\[d1755be/2016-02-27T16:30:37Z\\]$\n```\n\nCan you run Elasticsearch from this distribution with `TRACE` logging enabled, and after the NPE reproduces, share the output here?\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189714923","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189714923","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189714923,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTcxNDkyMw==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-27T19:59:09Z","updated_at":"2016-02-27T19:59:09Z","author_association":"NONE","body":"please see attached. it is a zip file but I had to rename it because for some reason github did not want to accept zip file\n\n[elasticsearch.zip.txt](https://github.com/elastic/elasticsearch/files/149530/elasticsearch.zip.txt)\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189763319","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189763319","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189763319,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTc2MzMxOQ==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-28T01:51:06Z","updated_at":"2016-02-28T01:51:06Z","author_association":"MEMBER","body":"@roytmana I think that you have a 1.x node running on your system and that's what is going on here. Can you confirm?\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189884716","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189884716","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189884716,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTg4NDcxNg==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-28T14:41:01Z","updated_at":"2016-02-28T14:41:01Z","author_association":"NONE","body":"@jasontedor not at the same time and in any case all my embedded elastic instances have unique cluster name.\nI am pretty sure no 1.x was running at the time I did the test but 2.2 could have. I will double-check everything again make sure no elastic is running and run it again\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/189885106","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-189885106","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":189885106,"node_id":"MDEyOklzc3VlQ29tbWVudDE4OTg4NTEwNg==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-28T14:45:35Z","updated_at":"2016-02-28T19:11:34Z","author_association":"MEMBER","body":"> @jasontedor not at the same time and in any case all my embedded elastic instances have unique cluster name.\n\n@roytmana The discovery process between the nodes will still take place, which combined with incompatible serialization is exactly what I think is going on here.\n\n> I am pretty sure no 1.x was running at the time I did the test but 2.2 could have. I will double-check everything again make sure no elastic is running and run it again\n\nI'm fairly convinced this situation can only happen if a 1.x node was running, not if another 2.x node was running, because I think the root cause is incompatible serialization.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190282962","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190282962","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190282962,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDI4Mjk2Mg==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T16:44:46Z","updated_at":"2016-02-29T16:44:46Z","author_association":"NONE","body":"I stopped every JVM on my computer and no elastic of any version is running on my computer or network. same issue. logs attached\n[elasticsearch.zip.txt](https://github.com/elastic/elasticsearch/files/151320/elasticsearch.zip.txt)\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190286043","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190286043","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190286043,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDI4NjA0Mw==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T16:53:38Z","updated_at":"2016-02-29T16:59:47Z","author_association":"MEMBER","body":"There is no `NullPointerException` in the logs that you attached, just `ConnectTransportException`s which are completely expected here. Now that you're sure that there are no other JVMs running on your system, this only confirms my theory even more. :)\n\n``` bash\n11:52:38 2d [jason:~/Downloads] $ unzip elasticsearch.zip.txt\nArchive:  elasticsearch.zip.txt\n  inflating: elasticsearch.log       \n11:52:39 2d [jason:~/Downloads] $ grep NullPointerException elasticsearch.log\n11:52:40 2d [jason:~/Downloads] 1 $ \n```\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190311884","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190311884","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190311884,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDMxMTg4NA==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T18:00:57Z","updated_at":"2016-02-29T18:00:57Z","author_association":"NONE","body":"but why all the exceptions connection?\nlet me start another 2.2 instance and run it again see if NPEs would come back\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190315281","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190315281","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190315281,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDMxNTI4MQ==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T18:09:30Z","updated_at":"2016-02-29T18:09:49Z","author_association":"MEMBER","body":"> but why all the exceptions connection?\n\nBecause when using the default network configuration, Elasticsearch tries to discover nodes also bound to localhost on ports 9301--9304. Since you don't have any other instances running, those discovery attempts will hit connection exceptions.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190316393","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190316393","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190316393,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDMxNjM5Mw==","user":{"login":"roytmana","id":2524911,"node_id":"MDQ6VXNlcjI1MjQ5MTE=","avatar_url":"https://avatars0.githubusercontent.com/u/2524911?v=4","gravatar_id":"","url":"https://api.github.com/users/roytmana","html_url":"https://github.com/roytmana","followers_url":"https://api.github.com/users/roytmana/followers","following_url":"https://api.github.com/users/roytmana/following{/other_user}","gists_url":"https://api.github.com/users/roytmana/gists{/gist_id}","starred_url":"https://api.github.com/users/roytmana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/roytmana/subscriptions","organizations_url":"https://api.github.com/users/roytmana/orgs","repos_url":"https://api.github.com/users/roytmana/repos","events_url":"https://api.github.com/users/roytmana/events{/privacy}","received_events_url":"https://api.github.com/users/roytmana/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T18:12:51Z","updated_at":"2016-02-29T18:12:51Z","author_association":"NONE","body":"No NPEs with 2.2 started 1.7.2 and NPEs are back. I guess you would need to look into it. Two separate clusters should not interfere with each other.\n\nWhy do you says connection exceptions are expected? They go away if I specify non loopback address for my node\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/190318012","html_url":"https://github.com/elastic/elasticsearch/issues/16810#issuecomment-190318012","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/16810","id":190318012,"node_id":"MDEyOklzc3VlQ29tbWVudDE5MDMxODAxMg==","user":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"created_at":"2016-02-29T18:18:19Z","updated_at":"2016-02-29T18:22:11Z","author_association":"MEMBER","body":"> No NPEs with 2.2 started 1.7.2 and NPEs are back.  \n\nI consider this confirmation of my theory. :)\n\n> I guess you would need to look into it. Two separate clusters should not interfere with each other.\n\nThey are not interfering with each other, the `NullPointerException` here ends up being harmless. If you do have mixed-versions running on the same network, you can avoid the two clusters even talking to each other at all by configuring unicast with host lists.\n\nEventually the node handshake will be extended by #15971 but there are no plans to make any changes to 1.x and 2.x along these lines. \n\n> Why do you says connection exceptions are expected? They go away if I specify non loopback address for my node\n\nBecause the attempted discovery only occurs if you are using the _default network configuration_.\n","performed_via_github_app":null}]