[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/293192644","html_url":"https://github.com/elastic/elasticsearch/issues/24023#issuecomment-293192644","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24023","id":293192644,"node_id":"MDEyOklzc3VlQ29tbWVudDI5MzE5MjY0NA==","user":{"login":"colings86","id":236731,"node_id":"MDQ6VXNlcjIzNjczMQ==","avatar_url":"https://avatars0.githubusercontent.com/u/236731?v=4","gravatar_id":"","url":"https://api.github.com/users/colings86","html_url":"https://github.com/colings86","followers_url":"https://api.github.com/users/colings86/followers","following_url":"https://api.github.com/users/colings86/following{/other_user}","gists_url":"https://api.github.com/users/colings86/gists{/gist_id}","starred_url":"https://api.github.com/users/colings86/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/colings86/subscriptions","organizations_url":"https://api.github.com/users/colings86/orgs","repos_url":"https://api.github.com/users/colings86/repos","events_url":"https://api.github.com/users/colings86/events{/privacy}","received_events_url":"https://api.github.com/users/colings86/received_events","type":"User","site_admin":false},"created_at":"2017-04-11T08:47:49Z","updated_at":"2017-04-11T08:47:49Z","author_association":"MEMBER","body":"@kujon I tried reproducing your bug on both the master branch and on the 2.4.4 release of Elasticsearch and I wasn't able to get the error you got above, instead the aggregations completed successfully. The script I used was:\r\n\r\n```\r\n\r\nPUT test\r\n{\r\n  \"settings\": {\r\n    \"number_of_shards\": 1,\r\n    \"number_of_replicas\": 0\r\n  },\r\n  \"mappings\": {\r\n    \"doc\": {\r\n      \"properties\": {\r\n        \"timestamp\": {\r\n          \"type\": \"date\"\r\n        }\r\n      }\r\n    }\r\n  }\r\n}\r\n\r\nPOST test/doc/1\r\n{\r\n  \"timestamp\": \"2017-01-01\",\r\n  \"price\": 100\r\n}\r\n\r\nPOST test/doc/2\r\n{\r\n  \"timestamp\": \"2017-01-02\",\r\n  \"price\": 200\r\n}\r\n\r\nPOST test/doc/3\r\n{\r\n  \"timestamp\": \"2017-01-03\",\r\n  \"price\": 300\r\n}\r\n\r\nPOST test/doc/4\r\n{\r\n  \"timestamp\": \"2017-01-04\",\r\n  \"price\": 400\r\n}\r\n\r\nPOST test/_search\r\n{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"histogram\": {\r\n      \"date_histogram\": {\r\n        \"field\": \"timestamp\",\r\n        \"interval\": \"day\"\r\n      },\r\n      \"aggs\": {\r\n        \"quantity\": {\r\n          \"sum\": {\r\n            \"field\": \"price\"\r\n          }\r\n        }\r\n      }\r\n    },\r\n    \"average_of_histogram\": {\r\n      \"avg_bucket\": {\r\n        \"buckets_path\": \"histogram>quantity\"\r\n      }\r\n    }\r\n  }\r\n}\r\n```\r\n\r\nCould you try running the above script on your environment and see if the error reproduces?  Could you also confirm the exact version of ES that you are running (e.g. 2.4.4)?\r\n\r\nThe curious thing here is that the buckets path should have already been validated as pointing to a suitable aggregation earlier than this so the cast attempted here should in theory be safe.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/302033586","html_url":"https://github.com/elastic/elasticsearch/issues/24023#issuecomment-302033586","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24023","id":302033586,"node_id":"MDEyOklzc3VlQ29tbWVudDMwMjAzMzU4Ng==","user":{"login":"colings86","id":236731,"node_id":"MDQ6VXNlcjIzNjczMQ==","avatar_url":"https://avatars0.githubusercontent.com/u/236731?v=4","gravatar_id":"","url":"https://api.github.com/users/colings86","html_url":"https://github.com/colings86","followers_url":"https://api.github.com/users/colings86/followers","following_url":"https://api.github.com/users/colings86/following{/other_user}","gists_url":"https://api.github.com/users/colings86/gists{/gist_id}","starred_url":"https://api.github.com/users/colings86/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/colings86/subscriptions","organizations_url":"https://api.github.com/users/colings86/orgs","repos_url":"https://api.github.com/users/colings86/repos","events_url":"https://api.github.com/users/colings86/events{/privacy}","received_events_url":"https://api.github.com/users/colings86/received_events","type":"User","site_admin":false},"created_at":"2017-05-17T09:16:04Z","updated_at":"2017-05-17T09:16:04Z","author_association":"MEMBER","body":"No further feedback, closing. If you are able to provide more feedback please comment on this issue and we can reopen","performed_via_github_app":null}]