[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/325587829","html_url":"https://github.com/elastic/elasticsearch/issues/24807#issuecomment-325587829","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24807","id":325587829,"node_id":"MDEyOklzc3VlQ29tbWVudDMyNTU4NzgyOQ==","user":{"login":"dbgrey44","id":26026698,"node_id":"MDQ6VXNlcjI2MDI2Njk4","avatar_url":"https://avatars2.githubusercontent.com/u/26026698?v=4","gravatar_id":"","url":"https://api.github.com/users/dbgrey44","html_url":"https://github.com/dbgrey44","followers_url":"https://api.github.com/users/dbgrey44/followers","following_url":"https://api.github.com/users/dbgrey44/following{/other_user}","gists_url":"https://api.github.com/users/dbgrey44/gists{/gist_id}","starred_url":"https://api.github.com/users/dbgrey44/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dbgrey44/subscriptions","organizations_url":"https://api.github.com/users/dbgrey44/orgs","repos_url":"https://api.github.com/users/dbgrey44/repos","events_url":"https://api.github.com/users/dbgrey44/events{/privacy}","received_events_url":"https://api.github.com/users/dbgrey44/received_events","type":"User","site_admin":false},"created_at":"2017-08-29T08:09:15Z","updated_at":"2017-08-29T08:12:12Z","author_association":"NONE","body":"Any update on this? I am also facing the same issue.\r\nI am also trying to query in a similar fashion as @KellyBennett.\r\n\r\nFrom the logs it looks like the 'precision' field can only be numeric type and thus fails when a string is parsed into it. \r\n\r\nIs the documentation incorrect or am I providing a wrong query here. Any help will be greatly appreciated.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/357389914","html_url":"https://github.com/elastic/elasticsearch/issues/24807#issuecomment-357389914","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24807","id":357389914,"node_id":"MDEyOklzc3VlQ29tbWVudDM1NzM4OTkxNA==","user":{"login":"wgottschalk","id":11728959,"node_id":"MDQ6VXNlcjExNzI4OTU5","avatar_url":"https://avatars0.githubusercontent.com/u/11728959?v=4","gravatar_id":"","url":"https://api.github.com/users/wgottschalk","html_url":"https://github.com/wgottschalk","followers_url":"https://api.github.com/users/wgottschalk/followers","following_url":"https://api.github.com/users/wgottschalk/following{/other_user}","gists_url":"https://api.github.com/users/wgottschalk/gists{/gist_id}","starred_url":"https://api.github.com/users/wgottschalk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/wgottschalk/subscriptions","organizations_url":"https://api.github.com/users/wgottschalk/orgs","repos_url":"https://api.github.com/users/wgottschalk/repos","events_url":"https://api.github.com/users/wgottschalk/events{/privacy}","received_events_url":"https://api.github.com/users/wgottschalk/received_events","type":"User","site_admin":false},"created_at":"2018-01-13T00:15:22Z","updated_at":"2018-01-13T00:15:22Z","author_association":"NONE","body":"I'm also noticing this bug on 5.5 as well.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/404102908","html_url":"https://github.com/elastic/elasticsearch/issues/24807#issuecomment-404102908","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24807","id":404102908,"node_id":"MDEyOklzc3VlQ29tbWVudDQwNDEwMjkwOA==","user":{"login":"vandanachadha","id":982568,"node_id":"MDQ6VXNlcjk4MjU2OA==","avatar_url":"https://avatars3.githubusercontent.com/u/982568?v=4","gravatar_id":"","url":"https://api.github.com/users/vandanachadha","html_url":"https://github.com/vandanachadha","followers_url":"https://api.github.com/users/vandanachadha/followers","following_url":"https://api.github.com/users/vandanachadha/following{/other_user}","gists_url":"https://api.github.com/users/vandanachadha/gists{/gist_id}","starred_url":"https://api.github.com/users/vandanachadha/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vandanachadha/subscriptions","organizations_url":"https://api.github.com/users/vandanachadha/orgs","repos_url":"https://api.github.com/users/vandanachadha/repos","events_url":"https://api.github.com/users/vandanachadha/events{/privacy}","received_events_url":"https://api.github.com/users/vandanachadha/received_events","type":"User","site_admin":false},"created_at":"2018-07-11T09:19:23Z","updated_at":"2018-07-11T09:19:23Z","author_association":"NONE","body":"I am using ES version 6,2.0, but still getting the same parsing error for \"precision\" if value is \"5m\" etc. Works ok if integer.","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/404197260","html_url":"https://github.com/elastic/elasticsearch/issues/24807#issuecomment-404197260","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/24807","id":404197260,"node_id":"MDEyOklzc3VlQ29tbWVudDQwNDE5NzI2MA==","user":{"login":"imotov","id":655851,"node_id":"MDQ6VXNlcjY1NTg1MQ==","avatar_url":"https://avatars3.githubusercontent.com/u/655851?v=4","gravatar_id":"","url":"https://api.github.com/users/imotov","html_url":"https://github.com/imotov","followers_url":"https://api.github.com/users/imotov/followers","following_url":"https://api.github.com/users/imotov/following{/other_user}","gists_url":"https://api.github.com/users/imotov/gists{/gist_id}","starred_url":"https://api.github.com/users/imotov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imotov/subscriptions","organizations_url":"https://api.github.com/users/imotov/orgs","repos_url":"https://api.github.com/users/imotov/repos","events_url":"https://api.github.com/users/imotov/events{/privacy}","received_events_url":"https://api.github.com/users/imotov/received_events","type":"User","site_admin":false},"created_at":"2018-07-11T14:48:53Z","updated_at":"2018-07-11T14:48:53Z","author_association":"MEMBER","body":"@vandanachadha it was fixed by #29273 As you can see from labels on the issue it was fixed only in 6.3.0 and above. So, it is expected to get the same parsing error in 6.2.0, which was released 2 months before the issue was fixed.","performed_via_github_app":null}]