{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/8887","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/8887/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/8887/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/8887/events","html_url":"https://github.com/elastic/elasticsearch/issues/8887","id":51595083,"node_id":"MDU6SXNzdWU1MTU5NTA4Mw==","number":8887,"title":"Old snapshot in cluster state but cannot be retrieved via _all","user":{"login":"ppf2","id":7216393,"node_id":"MDQ6VXNlcjcyMTYzOTM=","avatar_url":"https://avatars0.githubusercontent.com/u/7216393?v=4","gravatar_id":"","url":"https://api.github.com/users/ppf2","html_url":"https://github.com/ppf2","followers_url":"https://api.github.com/users/ppf2/followers","following_url":"https://api.github.com/users/ppf2/following{/other_user}","gists_url":"https://api.github.com/users/ppf2/gists{/gist_id}","starred_url":"https://api.github.com/users/ppf2/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ppf2/subscriptions","organizations_url":"https://api.github.com/users/ppf2/orgs","repos_url":"https://api.github.com/users/ppf2/repos","events_url":"https://api.github.com/users/ppf2/events{/privacy}","received_events_url":"https://api.github.com/users/ppf2/received_events","type":"User","site_admin":false},"labels":[{"id":143077482,"node_id":"MDU6TGFiZWwxNDMwNzc0ODI=","url":"https://api.github.com/repos/elastic/elasticsearch/labels/:Distributed/Snapshot/Restore","name":":Distributed/Snapshot/Restore","color":"0e8a16","default":false,"description":"Anything directly related to the `_snapshot/*` APIs"},{"id":23173,"node_id":"MDU6TGFiZWwyMzE3Mw==","url":"https://api.github.com/repos/elastic/elasticsearch/labels/%3Ebug","name":">bug","color":"b60205","default":false,"description":null}],"state":"closed","locked":false,"assignee":{"login":"imotov","id":655851,"node_id":"MDQ6VXNlcjY1NTg1MQ==","avatar_url":"https://avatars3.githubusercontent.com/u/655851?v=4","gravatar_id":"","url":"https://api.github.com/users/imotov","html_url":"https://github.com/imotov","followers_url":"https://api.github.com/users/imotov/followers","following_url":"https://api.github.com/users/imotov/following{/other_user}","gists_url":"https://api.github.com/users/imotov/gists{/gist_id}","starred_url":"https://api.github.com/users/imotov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imotov/subscriptions","organizations_url":"https://api.github.com/users/imotov/orgs","repos_url":"https://api.github.com/users/imotov/repos","events_url":"https://api.github.com/users/imotov/events{/privacy}","received_events_url":"https://api.github.com/users/imotov/received_events","type":"User","site_admin":false},"assignees":[{"login":"imotov","id":655851,"node_id":"MDQ6VXNlcjY1NTg1MQ==","avatar_url":"https://avatars3.githubusercontent.com/u/655851?v=4","gravatar_id":"","url":"https://api.github.com/users/imotov","html_url":"https://github.com/imotov","followers_url":"https://api.github.com/users/imotov/followers","following_url":"https://api.github.com/users/imotov/following{/other_user}","gists_url":"https://api.github.com/users/imotov/gists{/gist_id}","starred_url":"https://api.github.com/users/imotov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imotov/subscriptions","organizations_url":"https://api.github.com/users/imotov/orgs","repos_url":"https://api.github.com/users/imotov/repos","events_url":"https://api.github.com/users/imotov/events{/privacy}","received_events_url":"https://api.github.com/users/imotov/received_events","type":"User","site_admin":false}],"milestone":null,"comments":0,"created_at":"2014-12-10T18:44:42Z","updated_at":"2015-02-25T16:21:23Z","closed_at":"2015-02-25T16:21:22Z","author_association":"MEMBER","active_lock_reason":null,"body":"Unfortunately, we don't have exact details/timings for how this occurred.  From the information received (version 1.3.2), the S3 bucket tied to a S3 repository was inadvertently deleted at some point, and possibly while a snapshot was running.  As a result, when attempting to use the PUT command to update the repository definition in the cluster, the following message was received:\n\n```\n{\"error\":\"RemoteTransportException[[elasticsearch-elasticsearch7.localdomain][inet[/IP:9300]][cluster/repository/put]]; nested: ElasticsearchIllegalStateException[trying to modify or unregister repository that is currently used ]; \",\"status\":500}\n```\n\nAn attempt to use _all to retrieve the snapshots to see their statuses from the repository resulted in a bucket not found error:\n\n```\ncurl -XGET \"http://host:9200/_snapshot/production/_all\" \n{\"error\":\"RemoteTransportException[[elasticsearch-elasticsearch7.localdomain][inet[/IP:9300]][cluster/snapshot/get]]; nested: AmazonS3Exception[The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 87CD758CA1776085)]; \",\"status\":500}\n```\n\nAn attempt to delete the problem repository to start over failed as well:\n\n```\ncurl -XDELETE http://host:9200/_snapshot/production?pretty \n{ \n\"error\" : \"RemoteTransportException[[elasticsearch-elasticsearch7.localdomain][inet[/IP:9300]][cluster/repository/delete]]; nested: ElasticsearchIllegalStateException[trying to modify or unregister repository that is currently used ]; \", \n\"status\" : 500 \n} \n```\n\nAn attempt to create a different/new repository to take a snapshot also did not work:\n\n```\n'{\"error\":\"RemoteTransportException[[elasticsearch-elasticsearch7.localdomain][inet[/IP:9300]][cluster/snapshot/create]]; nested: ConcurrentSnapshotExecutionException[[production-v2:1209201414] a snapshot is already running]; \",\"status\":503}' \n```\n\nSince _all does not retrieve the outstanding snapshot information, we looked at the cluster state itself and saw that there is indeed a snapshot that appears to be stuck in INIT state:\n\n```\n    \"snapshots\" : {\n      \"snapshots\" : [ {\n        \"repository\" : \"production\",\n        \"snapshot\" : \"1207201400\",\n        \"include_global_state\" : true,\n        \"state\" : \"INIT\",\n        \"indices\" : [\n```\n\nWe subsequently was able to delete the snapshot using the snapshot API to recover from this.\n\nSo it sounds like there may be an issue with the _all API not able to retrieve a snapshot that is still in the cluster state.\n","closed_by":{"login":"imotov","id":655851,"node_id":"MDQ6VXNlcjY1NTg1MQ==","avatar_url":"https://avatars3.githubusercontent.com/u/655851?v=4","gravatar_id":"","url":"https://api.github.com/users/imotov","html_url":"https://github.com/imotov","followers_url":"https://api.github.com/users/imotov/followers","following_url":"https://api.github.com/users/imotov/following{/other_user}","gists_url":"https://api.github.com/users/imotov/gists{/gist_id}","starred_url":"https://api.github.com/users/imotov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imotov/subscriptions","organizations_url":"https://api.github.com/users/imotov/orgs","repos_url":"https://api.github.com/users/imotov/repos","events_url":"https://api.github.com/users/imotov/events{/privacy}","received_events_url":"https://api.github.com/users/imotov/received_events","type":"User","site_admin":false},"performed_via_github_app":null}